### ISSUE TITLE
Canned Responses doesn't work.

### ISSUE THREAD

**Issue by DeadLyBro** [edde746/shelter-plugins#1]
I don't tried other plugin but I tried canned responses and its not working. 
Screenshot:
![Screenshot_1](https://github.com/edde746/shelter-plugins/assets/31214077/3d2811f9-534f-419d-b1f9-4fd281cb6527)

More info: ( I guess it's unnecessary but: )
uwu/shelter-builds/src/index.ts
![Screenshot_2](https://github.com/edde746/shelter-plugins/assets/31214077/c92e959d-2719-43cc-96f5-92adb9bf669a)

**Comment by edde746** [comment]
Fixed by https://github.com/edde746/shelter-plugins/commit/934cf59642cda95f145f861d792555522aa12eb9 and https://github.com/edde746/shelter-plugins/commit/0bcee4af88163442ee514ac390cb35953e881ce6
