### ISSUE TITLE
gpt doesnt work

### ISSUE THREAD

**Issue by 1fbw** [edde746/shelter-plugins#2]
gpt no work
![image](https://github.com/user-attachments/assets/8d8c9132-b11a-4444-b088-161ea0434347)
![image](https://github.com/user-attachments/assets/92eec8bd-c2d5-4963-b22b-5c5cf5bdefc6)
![image](https://github.com/user-attachments/assets/82c7bf56-539b-49ee-85f1-70dc6f212ea5)
![image](https://github.com/user-attachments/assets/a016920a-3150-45ce-8c01-b833d83b1383)
![image](https://github.com/user-attachments/assets/26e7fe72-eae6-4e32-b3d8-3192facc378c)

 how fix

**Comment by edde746** [comment]
Check the network inspector to see if something is going wrong with the request

**Comment by 1fbw** [comment]
where?

**Comment by edde746** [comment]
https://developer.chrome.com/docs/devtools/network

**Comment by 1fbw** [comment]
ty, ill post results asap

**Comment by 1fbw** [comment]
![image](https://github.com/user-attachments/assets/7c51de30-0ac0-4ae1-aaef-dad1d27d06a0)
is this what u need?

**Comment by edde746** [comment]
It's what whoever feels like fixing it needs

**Comment by 1fbw** [comment]
lmao

**Comment by 1fbw** [comment]
so u wont fix it?

**Comment by 1fbw** [comment]
also this might be another issue
![image](https://github.com/user-attachments/assets/2fc8c3b8-69a4-4eb6-a0d5-7b219512135c)

**Comment by edde746** [comment]
> so u wont fix it?

Unless I feel like it, no.

**Comment by 1fbw** [comment]
sad

**Comment by 1fbw** [comment]
bro , ur shits just busted lmaooo

**Comment by 1fbw** [comment]
![image](https://github.com/user-attachments/assets/64c3d6ca-a000-4e2a-ad44-5d336ea64d9d)
![image](https://github.com/user-attachments/assets/a56f9334-0d31-4454-a59f-0e0e53a359f1)

**Comment by 1fbw** [comment]
yk, if u tell me what that line is supposed to do, i could try fxing it myself
![image](https://github.com/user-attachments/assets/f70e3724-7219-41e6-8898-84f191b55260)

**Comment by 1fbw** [comment]
g?

**Comment by 1fbw** [comment]
closed as "owner dev be lazy as fuck"
